name: Deploy Quartz

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [update-notes]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      # 拉取笔记仓库
      - name: Sync Content
        run: |
          rm -rf content/CFA-Notes
          git clone --depth 1 https://${{ secrets.PAT_TOKEN }}@github.com/Cedric9352/CFA-Notes.git content/CFA-Notes
          rm -rf content/CFA-Notes/.git
      
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npx quartz build
      - uses: actions/upload-pages-artifact@v5
        with:
          path: public
      - uses: actions/deploy-pages@v5
